version: "2.1"
services:
  db:
    build: db
    environment:
      - DEBUG=true

  backend:
    build: backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend